import Nav from "./components/Nav";
import "/public/css/style.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div>{children}</div>
      </body>
    </html>
  );
}
